version: '3.9'

networks:
  demo-tier:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - demo
    links:
      - demo
    ports:
      - "80:80"

  demo:
    build: ./deploy
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - NAME=demo
      - PORT=3000